export const GET_ARTISTES_SUCCESS = 'GET_ARTISTES_SUCCESS';
export const GET_ARTISTES_FAILED = 'GET_ARTISTES_FAILED';

export const GET_INFORMATIONS_SUCCESS = 'GET_INFORMATIONS_SUCCESS';
export const GET_INFORMATIONS_FAILED = 'GET_INFORMATIONS_FAILED';

export const GET_BOUTIQUES_SUCCESS = 'GET_BOUTIQUES_SUCCESS';
export const GET_BOUTIQUES_FAILED = 'GET_BOUTIQUES_FAILED';

export const GET_BUVETTES_SUCCESS = 'GET_BUVETTES_SUCCESS';
export const GET_BUVETTES_FAILED = 'GET_BUVETTES_FAILED';

export const GET_CONCERTS_SUCCESS = 'GET_CONCERTS_SUCCESS';
export const GET_CONCERTS_FAILED = 'GET_CONCERTS_FAILED';

export const GET_FAQS_SUCCESS = 'GET_FAQ_SUCCESS';
export const GET_FAQS_FAILED = 'GET_FAQ_FAILED';

export const GET_SCENES_SUCCESS = 'GET_SCENES_SUCCESS';
export const GET_SCENES_FAILED = 'GET_SCENES_FAILED';

export const GET_STANDS_SUCCESS = 'GET_STANDS_SUCCESS';
export const GET_STANDS_FAILED = 'GET_STANDS_FAILED';

export const GET_PARKINGS_SUCCESS = 'GET_PARKINGS_SUCCESS';
export const GET_PARKINGS_FAILED = 'GET_PARKINGS_FAILED';


export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
export const PUSH_SUCCESS = "PUSH_SUCCESS";
export const PUSH_ERROR = "PUSH_ERROR";
export const PULL_SUCCESS = "PULL_SUCCESS";

export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
